#!/bin/bash

set -e

source ~/Documents/resources.d/phoenixrc 

sudo POSTGRES_USER_PHOENIX=$POSTGRES_USER_PHOENIX \
     POSTGRES_PASSWORD_PHOENIX=$POSTGRES_PASSWORD_PHOENIX \
     POSTGRES_DB_PHOENIX=$POSTGRES_DB_PHOENIX \
     PHOENIXDB_DATABASE=$PHOENIXDB_DATABASE \
     PHOENIXDB_USER=$PHOENIXDB_USER \
     PHOENIXDB_PASSWORD=$PHOENIXDB_PASSWORD \
     docker compose start

