networks:
  searxng_net:

volumes:
  caddy-data:
  caddy-config:
  caddy-etc:
  valkey-data2:
  searxng-etc:

services:
  caddy:
    container_name: caddy
    hostname: caddy
    image: caddy:2.7.6-alpine
    pull_policy: missing
    restart: unless-stopped
    networks:
      - searxng_net
    volumes:
      - caddy-etc:/etc/caddy:rw
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  redis:
    container_name: redis
    hostname: redis
    image: valkey/valkey:8.1-alpine3.21
    pull_policy: missing
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng_net
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    hostname: searxng
    image: searxng/searxng:2025.4.18-5ae3b3f17
    pull_policy: missing
    restart: unless-stopped
    networks:
      - searxng_net
    ports:
      - "8080:8080"
    volumes:
      - searxng-etc:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
